org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.20.1
forge_version=47.4.10
mod_id=nbtech2fix
mod_name=\u8D85\u7EA7\u725B\u903C\u7684\u79D1\u6280\u6574\u5408\u53052 \u4E00\u4E9B\u4FEE\u590D
mod_license=All Rights Reserved
mod_version=1.6.0
mod_group_id=nbtech2.fix
