org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.222
loader_version_range=[1,)

mod_id=nbtech2fix
mod_name=\u8d85\u7ea7\u725b\u903c\u7684\u79d1\u6280\u6574\u5408\u53052 \u4e00\u4e9b\u4fee\u590d
mod_license=All Rights Reserved
mod_version=1.6.0snapshot2
mod_group_id=nbtech2.fix
